window.STUDENTS = [
  {
    id: "aditya",
    name: "Aditya Sharma",
    degree: "MSc Systems & Control",
    status: "Alumni",
    country: "India",
    countryCode: "IN",
    degreeLevel: "Master's",
    areaOfStudy: "Engineering",
    languages: ["English", "Hindi", "Dutch"],
    hobbies: ["#Study", "#HorseRiding", "#Cooking"],
    about:
      "I completed my master's at Harborview and now work in robotics. Happy to talk about thesis projects, Dutch culture, and finding housing near campus.",
    availability: "Usually available weekdays",
    avatar: "https://i.pravatar.cc/150?u=aditya-sharma",
  },
  {
    id: "sophie",
    name: "Megan Walsh",
    degree: "BSc Computer Science",
    status: "Bachelor's program",
    country: "United States",
    countryCode: "US",
    degreeLevel: "Bachelor's",
    areaOfStudy: "Computer Science",
    languages: ["English", "Spanish"],
    hobbies: ["#Hackathons", "#Basketball", "#Photography"],
    about:
      "From Chicago, now in my second year studying AI and software engineering. Happy to chat about campus clubs, internships in the US, and adjusting to student life abroad.",
    availability: "Open most afternoons",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "maria",
    name: "Lin Wei",
    degree: "MSc Sustainable Energy",
    status: "Master's program",
    country: "China",
    countryCode: "CN",
    degreeLevel: "Master's",
    areaOfStudy: "Sustainability",
    languages: ["English", "Mandarin", "Cantonese"],
    hobbies: ["#ClimateAction", "#Badminton", "#Travel"],
    about:
      "From Guangzhou, researching solar integration in smart grids. Ask me about scholarships, lab work, and what it's like moving from China to study overseas.",
    availability: "Best on Tue & Thu",
    avatar: "assets/lin-wei.jpg",
  },
  {
    id: "james",
    name: "James Mitchell",
    degree: "BSc Mechanical Engineering",
    status: "Bachelor's program",
    country: "United States",
    countryCode: "US",
    degreeLevel: "Bachelor's",
    areaOfStudy: "Engineering",
    languages: ["English"],
    hobbies: ["#FormulaStudent", "#Basketball", "#Music"],
    about:
      "From Austin, Texas — I lead our Formula Student team. Ask me about hands-on engineering, co-op placements, and making the most of an international degree.",
    availability: "Weekends & evenings",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
  },
  {
    id: "yuki",
    name: "Yuki Tanaka",
    degree: "MSc Data Science",
    status: "Master's program",
    country: "Japan",
    countryCode: "JP",
    degreeLevel: "Master's",
    areaOfStudy: "Computer Science",
    languages: ["English", "Japanese"],
    hobbies: ["#MachineLearning", "#Anime", "#Coffee"],
    about:
      "Data science enthusiast working on NLP research. I can help with application essays, picking electives, and navigating grad school expectations.",
    availability: "Flexible — book anytime",
    avatar: "https://i.pravatar.cc/150?u=yuki-tanaka",
  },
  {
    id: "emma",
    name: "Emma Chen",
    degree: "BSc Biomedical Engineering",
    status: "Bachelor's program",
    country: "China",
    countryCode: "CN",
    degreeLevel: "Bachelor's",
    areaOfStudy: "Health Sciences",
    languages: ["English", "Mandarin"],
    hobbies: ["#Research", "#Running", "#Baking"],
    about:
      "From Shanghai, on a pre-med track with a focus on tissue engineering. Reach out about lab opportunities, studying in China vs. abroad, and campus wellness resources.",
    availability: "Mornings work best",
    avatar: "assets/emma-chen.jpg",
  },
  {
    id: "lucas",
    name: "Lucas Müller",
    degree: "MSc Architecture",
    status: "Alumni",
    country: "Germany",
    countryCode: "DE",
    degreeLevel: "Master's",
    areaOfStudy: "Design",
    languages: ["English", "German", "Dutch"],
    hobbies: ["#UrbanDesign", "#Sketching", "#Hiking"],
    about:
      "Alumni now at a design studio in Rotterdam. I enjoy mentoring applicants on portfolios, studio culture, and career paths after graduation.",
    availability: "Available this week",
    avatar: "https://i.pravatar.cc/150?u=lucas-muller",
  },
  {
    id: "priya",
    name: "Priya Nair",
    degree: "PhD Chemical Engineering",
    status: "Doctoral program",
    country: "India",
    countryCode: "IN",
    degreeLevel: "PhD",
    areaOfStudy: "Engineering",
    languages: ["English", "Hindi", "Malayalam"],
    hobbies: ["#LabLife", "#ClassicalDance", "#Cooking"],
    about:
      "Third-year PhD working on green catalysts. Happy to discuss funding, supervisor relationships, and the realities of doctoral research.",
    availability: "Wed & Fri preferred",
    avatar: "https://i.pravatar.cc/150?u=priya-nair",
  },
];
