window.VIDEO_POSTS = [
  {
    id: "housing-sophie",
    studentId: "sophie",
    title: "Day in my life as a CS student at Harborview",
    snippet: "From morning lecture to late-night coding — a real look at campus life as a US student abroad.",
    topic: "Student life",
    areaOfStudy: "Computer Science",
    platform: "tiktok",
    publishedAt: "2026-05-28",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.tiktok.com",
  },
  {
    id: "housing-maria",
    studentId: "maria",
    title: "How I found affordable housing near campus",
    snippet: "Three tips that helped me settle in after moving from China to Harborview.",
    topic: "Housing",
    areaOfStudy: "Sustainability",
    platform: "instagram",
    publishedAt: "2026-05-22",
    thumbnail: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.instagram.com",
  },
  {
    id: "formula-james",
    studentId: "james",
    title: "Inside our Formula Student garage",
    snippet: "A quick tour of where we build the car and what freshmen can get involved in.",
    topic: "Campus",
    areaOfStudy: "Engineering",
    platform: "tiktok",
    publishedAt: "2026-05-15",
    thumbnail: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.tiktok.com",
  },
  {
    id: "lab-emma",
    studentId: "emma",
    title: "My morning biomedical lab routine",
    snippet: "What a typical lab morning looks like before classes start.",
    topic: "Student life",
    areaOfStudy: "Health Sciences",
    platform: "instagram",
    publishedAt: "2026-05-10",
    thumbnail: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.instagram.com",
  },
  {
    id: "tools-yuki",
    studentId: "yuki",
    title: "3 data science tools I wish I knew in year one",
    snippet: "Short list of apps and workflows that made my master's way easier.",
    topic: "Study tips",
    areaOfStudy: "Computer Science",
    platform: "tiktok",
    publishedAt: "2026-05-03",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.tiktok.com",
  },
  {
    id: "grad-aditya",
    studentId: "aditya",
    title: "Grad school advice nobody tells you",
    snippet: "Thesis supervisors, networking, and what I'd do differently.",
    topic: "Careers",
    areaOfStudy: "Engineering",
    platform: "instagram",
    publishedAt: "2026-04-26",
    thumbnail: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.instagram.com",
  },
  {
    id: "studio-lucas",
    studentId: "lucas",
    title: "Studio culture at Harborview architecture",
    snippet: "Pin-ups, critiques, and how we present work — a peek behind the scenes.",
    topic: "Campus",
    areaOfStudy: "Design",
    platform: "tiktok",
    publishedAt: "2026-04-18",
    thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.tiktok.com",
  },
  {
    id: "phd-priya",
    studentId: "priya",
    title: "PhD lab vlog: a day with green catalysts",
    snippet: "Realistic look at experiments, meetings, and coffee breaks in the lab.",
    topic: "Student life",
    areaOfStudy: "Engineering",
    platform: "instagram",
    publishedAt: "2026-04-12",
    thumbnail: "https://images.unsplash.com/photo-1532187863486-abf9db881854?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.instagram.com",
  },
  {
    id: "scholarship-maria",
    studentId: "maria",
    title: "How I got my sustainability scholarship",
    snippet: "Application timeline, essay tips, and what the committee cared about.",
    topic: "Careers",
    areaOfStudy: "Sustainability",
    platform: "tiktok",
    publishedAt: "2026-04-05",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&h=800&fit=crop",
    videoSrc: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    externalUrl: "https://www.tiktok.com",
  },
];
